// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCK6dZEgUVGtiwYuBj4WMn99Gkw8OcfCX4',
//     appId: '1:367348845694:web:a1e65eec423bca85e65c2f',
//     messagingSenderId: '367348845694',
//     projectId: 'mdq-c-23ed2',
//     authDomain: 'mdq-c-23ed2.firebaseapp.com',
//     storageBucket: 'mdq-c-23ed2.firebasestorage.app',
//     measurementId: 'G-K8BXVT8FTR',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCjUnaa0eXkj_gbhNEVFDMrnYqHc5bLwRI',
//     appId: '1:367348845694:android:f6c8f5d7b6f90b48e65c2f',
//     messagingSenderId: '367348845694',
//     projectId: 'mdq-c-23ed2',
//     storageBucket: 'mdq-c-23ed2.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAayodxCdGlACmqxim39frzTSzMG9i_EY0',
//     appId: '1:367348845694:ios:b6bfb1bacddfbe71e65c2f',
//     messagingSenderId: '367348845694',
//     projectId: 'mdq-c-23ed2',
//     storageBucket: 'mdq-c-23ed2.firebasestorage.app',
//     iosBundleId: 'com.example.listdemo',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAayodxCdGlACmqxim39frzTSzMG9i_EY0',
//     appId: '1:367348845694:ios:b6bfb1bacddfbe71e65c2f',
//     messagingSenderId: '367348845694',
//     projectId: 'mdq-c-23ed2',
//     storageBucket: 'mdq-c-23ed2.firebasestorage.app',
//     iosBundleId: 'com.example.listdemo',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCK6dZEgUVGtiwYuBj4WMn99Gkw8OcfCX4',
//     appId: '1:367348845694:web:45559d000c7f1f0ae65c2f',
//     messagingSenderId: '367348845694',
//     projectId: 'mdq-c-23ed2',
//     authDomain: 'mdq-c-23ed2.firebaseapp.com',
//     storageBucket: 'mdq-c-23ed2.firebasestorage.app',
//     measurementId: 'G-0RYGWW459W',
//   );
// }
